# Generated by Django 6.0.7 on 2026-09-23 18:14

import apps.common.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_is_cheat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardimage',
            name='image',
            field=models.ImageField(storage=apps.common.storage.public_storage, upload_to=apps.common.storage.UniqueUploadTo('rewards/')),
        ),
    ]
