# Generated by Django 6.0.7 on 2026-07-09 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LevelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('props_json_schema', models.JSONField()),
            ],
            options={
                'db_table': 'level_types',
            },
        ),
        migrations.CreateModel(
            name='Mascot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('idle_asset_path', models.CharField(max_length=255)),
                ('zero_star_asset_path', models.CharField(db_column='0_star_asset_path', max_length=255)),
                ('one_star_asset_path', models.CharField(db_column='1_star_asset_path', max_length=255)),
                ('two_star_asset_path', models.CharField(db_column='2_star_asset_path', max_length=255)),
                ('three_star_asset_path', models.CharField(db_column='3_star_asset_path', max_length=255)),
            ],
            options={
                'db_table': 'mascots',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(db_index=True)),
                ('layer', models.CharField(choices=[('typing', 'Typing'), ('education', 'Education'), ('locked', 'Locked')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('title_font_size', models.PositiveIntegerField()),
                ('background_asset_path', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'units',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(db_index=True)),
                ('layer', models.CharField(choices=[('typing', 'Typing'), ('education', 'Education'), ('locked', 'Locked')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('level_props', models.JSONField()),
                ('splash_background_asset_path', models.CharField(max_length=255)),
                ('splash_button_color', models.BigIntegerField(blank=True, null=True)),
                ('splash_button_text_color', models.BigIntegerField(blank=True, null=True)),
                ('splash_level_font_color', models.BigIntegerField(blank=True, null=True)),
                ('splash_level_title_color', models.BigIntegerField(blank=True, null=True)),
                ('show_mascot_on_splash', models.BooleanField(default=False)),
                ('level_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='levels', to='game.leveltype')),
                ('mascot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='levels', to='game.mascot')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='game.unit')),
            ],
            options={
                'db_table': 'levels',
                'ordering': ['unit_id', 'sort_order', 'id'],
            },
        ),
    ]
