# Generated by Django 6.0.7 on 2026-07-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='layer',
            field=models.CharField(choices=[('typing', 'Typing'), ('education', 'Education'), ('game', 'Game')], max_length=20),
        ),
        migrations.AlterField(
            model_name='unit',
            name='layer',
            field=models.CharField(choices=[('typing', 'Typing'), ('education', 'Education'), ('game', 'Game')], max_length=20),
        ),
    ]
