# Generated by Django 6.0.7 on 2026-07-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_level_type_as_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='level_type',
            field=models.CharField(choices=[('education-letter-grid', 'Education letter grid')], max_length=255),
        ),
    ]
