# Generated by Django 6.0.7 on 2026-07-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_level_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='level_type',
            field=models.CharField(max_length=255),
        ),
    ]
