# Generated by Django 6.0.7 on 2026-07-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_remove_level_type_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='backdrop_color',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='level',
            name='background_asset_path',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='unit',
            name='subtitle_font_color',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='subtitle_font_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='subtitle_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='title_font_color',
            field=models.BigIntegerField(default=16777215),
        ),
        migrations.AddField(
            model_name='unit',
            name='title_is_curved',
            field=models.BooleanField(default=False),
        ),
    ]
