# Generated by Django 6.0.7 on 2026-07-21 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_unit_level_presentation_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='background_asset_path',
        ),
    ]
