# Generated by Django 6.0.7 on 2026-07-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='target_letter',
            field=models.CharField(max_length=255),
        ),
    ]
