# Generated by Django 6.0.7 on 2026-07-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_rename_word_file_to_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='translation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='target_letter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
