# Generated by Django 6.0.7 on 2026-07-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_word_translation_alter_word_target_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='is_tutorial_word',
            field=models.BooleanField(default=False),
        ),
    ]
