# Generated by Django 6.0.7 on 2026-07-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_word_is_tutorial_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='words/audio/'),
        ),
    ]
