# Generated by Django 6.0.7 on 2026-07-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_word_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='words/'),
        ),
    ]
