# Generated by Django 6.0.7 on 2026-09-20 07:18

import apps.game.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_word_audio_split'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('issue', 'Issue'), ('new_feature', 'New feature'), ('content', 'Content'), ('other', 'Other')], max_length=32)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=apps.game.models.feedback_image_upload_to)),
                ('screen', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feedback_reports',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
