# Generated by Django 6.0.7 on 2026-09-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0022_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="is_resolved",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
