# Generated by Django 6.0.7 on 2026-09-23 18:14

import apps.common.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_feedback_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascot',
            name='idle_image',
            field=models.ImageField(storage=apps.common.storage.public_storage, upload_to=apps.common.storage.UniqueUploadTo('mascots/')),
        ),
        migrations.AlterField(
            model_name='mascot',
            name='one_star_image',
            field=models.ImageField(storage=apps.common.storage.public_storage, upload_to=apps.common.storage.UniqueUploadTo('mascots/')),
        ),
        migrations.AlterField(
            model_name='mascot',
            name='sad_image',
            field=models.ImageField(storage=apps.common.storage.public_storage, upload_to=apps.common.storage.UniqueUploadTo('mascots/')),
        ),
        migrations.AlterField(
            model_name='mascot',
            name='three_star_image',
            field=models.ImageField(storage=apps.common.storage.public_storage, upload_to=apps.common.storage.UniqueUploadTo('mascots/')),
        ),
        migrations.AlterField(
            model_name='mascot',
            name='two_star_image',
            field=models.ImageField(storage=apps.common.storage.public_storage, upload_to=apps.common.storage.UniqueUploadTo('mascots/')),
        ),
        migrations.AlterField(
            model_name='mascot',
            name='zero_star_image',
            field=models.ImageField(storage=apps.common.storage.public_storage, upload_to=apps.common.storage.UniqueUploadTo('mascots/')),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='audio',
            field=models.FileField(blank=True, null=True, storage=apps.common.storage.public_storage, upload_to=apps.common.storage.UniqueUploadTo('sentences/audio/')),
        ),
        migrations.AlterField(
            model_name='word',
            name='education_audio',
            field=models.FileField(blank=True, null=True, storage=apps.common.storage.public_storage, upload_to=apps.common.storage.UniqueUploadTo('words/audio/')),
        ),
        migrations.AlterField(
            model_name='word',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=apps.common.storage.public_storage, upload_to=apps.common.storage.UniqueUploadTo('words/')),
        ),
        migrations.AlterField(
            model_name='word',
            name='standard_audio',
            field=models.FileField(blank=True, null=True, storage=apps.common.storage.public_storage, upload_to=apps.common.storage.UniqueUploadTo('words/audio/standard/')),
        ),
    ]
